/**
 * JJ Swim Lab — training-methods.ts
 * 확장된 훈련법 카탈로그 (20+ 종류)
 */

import { TrainingMethod, Zone } from './swim-glossary';

export const TRAINING_METHODS: TrainingMethod[] = [
  { id:'descend', name:'Descend(디센딩)',
    definition:'반복을 거듭할수록 점진 가속.',
    whenToUse:['템포 감각','후반 가속'],
    goals:['분배 능력','피니시 품질'],
    pros:['페이스 제어 능력↑'],
    cons:['첫 반복 과감속 시 품질↓'],
    cautions:['가속 폭 과대 금지'],
    zones:['Z3','Z4'],
    examples25:['4×100 @ CSS+6″→+4″→+2″→CSS, r20″'],
    examples50:['6×50 @ CSS+6″→CSS−2″, r25″'],
    recommendedDrillIds:['fs_6_1_6','fs_fingertip'] },

  { id:'ascend', name:'Ascend(어센딩)',
    definition:'반복을 거듭할수록 점진 감속.',
    whenToUse:['하드세트 후 회복','폼 점검'],
    goals:['회복/기술 유지'],
    pros:['과훈련 방지'],
    cons:['자극 낮음'],
    cautions:['너무 느려 폼 붕괴 금지'],
    zones:['Z1','Z2'],
    examples25:['6×50 easy→mod, r15″'],
    examples50:['4×100 ascend 1→4, r20″'],
    recommendedDrillIds:['fs_fist','fs_scull1'] },

  { id:'build', name:'Build(빌드)',
    definition:'한 반복 내에서 초반→후반 가속.',
    whenToUse:['레이스 전개','스플릿 감각'],
    goals:['후반 가속'],
    pros:['레이스 전이 용이'],
    cons:['후반 급가속 오버폼 위험'],
    cautions:['균등 증속'],
    zones:['Z3','Z4'],
    examples25:['8×50 (내부 build), r20″'],
    examples50:['6×100 build within 100, r20″'],
    recommendedDrillIds:['fs_6_1_6','fs_single_arm'] },

  { id:'neg_split', name:'Negative Split',
    definition:'후반이 전반보다 빠름.',
    whenToUse:['배분 연습','지속 지구력'],
    goals:['에너지 관리','후반 품질'],
    pros:['지속성 향상'],
    cons:['전반 과저속 시 손해'],
    cautions:['급격 가속 금지'],
    zones:['Z3'],
    examples25:['6×100 (1–50 CSS+6″ / 51–100 CSS−2″)'],
    examples50:['4×200 네거티브 스플릿, r25″'],
    recommendedDrillIds:['fs_fingertip','fs_scull2'] },

  { id:'even', name:'Even Split',
    definition:'전반=후반 동일 페이스.',
    whenToUse:['지속 훈련','페이스 안정'],
    goals:['일정 페이스'],
    pros:['안정성↑'],
    cons:['지루함'],
    cautions:['형식적 유지 금지'],
    zones:['Z2','Z3'],
    examples25:['8×100 @ CSS+4″, r15–20″'],
    examples50:['12×50 @ CSS+4″, r15″'],
    recommendedDrillIds:['fs_6_1_6'] },

  { id:'ladder', name:'Ladder(사다리)',
    definition:'거리 단계 ↑ 또는 ↓.',
    whenToUse:['지속 지구력','심리적 몰입'],
    goals:['페이스 유지','거리 내성'],
    pros:['단조로움 감소'],
    cons:['중후반 피로'],
    cautions:['레스트 일정'],
    zones:['Z2','Z3'],
    examples25:['100-200-300-200-100 @ CSS+4~6″'],
    examples50:['50-100-150-200-150-100-50'],
    recommendedDrillIds:['fs_6_1_6'] },

  { id:'pyramid', name:'Pyramid(피라미드)',
    definition:'대칭 구조(오르내림).',
    whenToUse:['중간 피크 설정'],
    goals:['중거리 내성','페이스 유지'],
    pros:['구성 명확'],
    cons:['피크 피로'],
    cautions:['피크 휴식 확보'],
    zones:['Z2','Z3'],
    examples25:['피라미드 @ CSS±0~+4″, r15–20″'],
    examples50:['50-100-150-200-150-100-50'],
    recommendedDrillIds:['fs_scull1','fs_scull2'] },

  { id:'broken', name:'Broken Swims',
    definition:'긴 거리를 잘라 레스트 삽입(레이스페이스 품질↑).',
    whenToUse:['RP 품질 향상'],
    goals:['유효 속도↑'],
    pros:['고품질 반복'],
    cons:['총부하↑ 가능'],
    cautions:['레스트 과다 주의'],
    zones:['Z4','Z5'],
    examples25:['200 broken = 3×50+1×50 @ RP, r10–15″'],
    examples50:['400 broken = 4×50×2 @ RP, r10–15″'],
    recommendedDrillIds:['fs_tarzan'] },

  { id:'fartlek', name:'Fartlek(가변 페이스)',
    definition:'구간마다 속도 랜덤 변조.',
    whenToUse:['오픈워터','상황 대응'],
    goals:['변속 대응'],
    pros:['흥미↑','자율성↑'],
    cons:['측정성↓'],
    cautions:['과부하 주의'],
    zones:['Z2','Z3','Z4'],
    examples25:['400 cont. ez/mod/fast 랜덤 콜'],
    examples50:['8×50 랜덤 페이스'],
    recommendedDrillIds:['fs_tarzan'] },

  { id:'tempo_trainer', name:'Tempo Trainer',
    definition:'SR/템포를 메트로놈 비프에 맞춤.',
    whenToUse:['스트로크율 일정화'],
    goals:['경제성','리듬'],
    pros:['오버턴 방지'],
    cons:['기기 의존'],
    cautions:['템포 과감소 금지'],
    zones:['Z2','Z3'],
    examples25:['6×100 @ 비프×n'],
    examples50:['8×50 SR 고정'],
    recommendedDrillIds:['fs_fist'] },

  { id:'threshold', name:'Threshold/CSS',
    definition:'임계 전후 템포 유지.',
    whenToUse:['경기력 핵심'],
    goals:['지속 템포'],
    pros:['기록 가속'],
    cons:['누적피로'],
    cautions:['주당 빈도 관리'],
    zones:['Z3'],
    examples25:['8×100 @ CSS±, r15–20″'],
    examples50:['5×200 @ CSS±, r20–25″'],
    recommendedDrillIds:['fs_6_1_6'] },

  { id:'vo2', name:'VO₂ 인터벌',
    definition:'CSS보다 빠른 간헐 고강도.',
    whenToUse:['속도 내성','VO₂max'],
    goals:['고속/내성'],
    pros:['기록 가속'],
    cons:['리스크↑'],
    cautions:['어지럼/혈압 주의'],
    zones:['Z4'],
    examples25:['12×50 @ CSS−2~5″, r25–40″'],
    examples50:['8×100 @ CSS−2~4″, r30–45″'],
    recommendedDrillIds:['fs_single_arm'] },

  { id:'sprint', name:'Sprint/Power',
    definition:'전력 스프린트 + 충분 휴식.',
    whenToUse:['신경근 파워','브레이크아웃'],
    goals:['최고속'],
    pros:['피크 속도↑'],
    cons:['회복시간↑'],
    cautions:['어깨/발목 부하'],
    zones:['Z5'],
    examples25:['8×25 all-out, full rest'],
    examples50:['6×50 (25 fast/25 easy)'],
    recommendedDrillIds:['fs_streamline'] },

  { id:'kick', name:'Kick 전용',
    definition:'하체 추진 강화(보드/핀).',
    whenToUse:['킥 약점 보강'],
    goals:['하체 파워'],
    pros:['분리 훈련'],
    cons:['허리/발목 부하'],
    cautions:['요통/아킬레스 관리'],
    zones:['Z2','Z3'],
    examples25:['8×50 kick, r20″'],
    examples50:['6×100 kick, r25″'],
    recommendedDrillIds:[] },

  { id:'pull', name:'Pull 전용',
    definition:'상지 추진 강화(부이/패들).',
    whenToUse:['팔 추진/정렬'],
    goals:['상지 파워/경제성'],
    pros:['정렬 안정'],
    cons:['어깨 부하'],
    cautions:['패들 용량 보수'],
    zones:['Z2','Z3'],
    examples25:['6×100 pull, r20″'],
    examples50:['8×50 pull, r15″'],
    recommendedDrillIds:['fs_fist'] },

  { id:'drillswim', name:'Drill/Swim by 25',
    definition:'25 드릴 + 25 수영 교대 전이.',
    whenToUse:['드릴 효과 전이'],
    goals:['기술→수영 전환'],
    pros:['즉시 전이'],
    cons:['세팅 번거로움'],
    cautions:['드릴 과다 금지'],
    zones:['Z1','Z2'],
    examples25:['(25 drill + 25 swim) × 6'],
    examples50:['(25 drill + 25 swim) × 8'],
    recommendedDrillIds:['fs_6_1_6','fs_fingertip'] },

  { id:'choice', name:'Choice/Stations',
    definition:'코스별 과제 상이한 순환식.',
    whenToUse:['팀 세션 다양화'],
    goals:['흥미/몰입'],
    pros:['동기↑'],
    cons:['측정성↓'],
    cautions:['안전 감독'],
    zones:['Z1','Z2','Z3'],
    examples25:['3개 스테이션×3라운드'],
    examples50:['4개 스테이션×2라운드'],
    recommendedDrillIds:[] },

  { id:'pace_clock', name:'Pace Clock Skills',
    definition:'페이스 클록 읽기·자율 페이스 훈련.',
    whenToUse:['자율 능력'],
    goals:['페이스 제어'],
    pros:['자율성↑'],
    cons:['학습 필요'],
    cautions:['과집착 금지'],
    zones:['Z1','Z2','Z3'],
    examples25:['홀드/온 변형 세트'],
    examples50:['홀드 세트'],
    recommendedDrillIds:[] },

  { id:'rp25', name:'Race Pace 25s',
    definition:'25m 단위 RP 반복으로 품질 극대화.',
    whenToUse:['중·단거리 준비'],
    goals:['레이스 페이스 적응'],
    pros:['고품질/짧은 피로'],
    cons:['총거리 부족 가능'],
    cautions:['레스트 충분'],
    zones:['Z4','Z5'],
    examples25:['16×25 @ RP, r20–30″'],
    examples50:['12×50 (25 fast/25 ez) @ RP half'],
    recommendedDrillIds:['fs_tarzan','fl_3_3_3'] },

  { id:'turn_focus', name:'Turn Focus',
    definition:'턴/브레이크아웃 중심 세트.',
    whenToUse:['풀 코스 효율'],
    goals:['접근·회전·푸시오프 개선'],
    pros:['유효 속도↑'],
    cons:['현기증 가능'],
    cautions:['짧게 빈번히'],
    zones:['Z2','Z3'],
    examples25:['10×25 focus = 마지막 5m 턴 품질, r20″'],
    examples50:['8×50 (25 in + turn + 25 out)'],
    recommendedDrillIds:['turn_flip','st_streamline'] },

  { id:'sr_lock', name:'Stroke Rate Lock',
    definition:'SR 범위를 고정하고 페이스 유지 훈련.',
    whenToUse:['경제성','리듬 안정'],
    goals:['SR-Pace 결합'],
    pros:['일관성↑'],
    cons:['속도 한계'],
    cautions:['과도한 SR 금지'],
    zones:['Z2','Z3'],
    examples25:['8×50 SR=34 고정, r20″'],
    examples50:['6×100 SR=36, r25″'],
    recommendedDrillIds:['fs_fist','tempo_trainer'] },

  { id:'hypoxic_set', name:'Hypoxic(하이폭식)',
    definition:'호흡 간격 제한 기반 세트.',
    whenToUse:['헤드포지션·리듬'],
    goals:['CO₂ 내성','헤드 컨트롤'],
    pros:['리듬감'],
    cons:['어지럼 위험'],
    cautions:['의료 위험군 회피'],
    zones:['Z2','Z3'],
    examples25:['3/5/7 래더 6×25'],
    examples50:['25m 무호흡+25 easy × 6'],
    recommendedDrillIds:['fs_6_1_6'] },

  { id:'aerobic_mix', name:'Aerobic Mix',
    definition:'EN1/EN2 블록 혼합 지속 훈련.',
    whenToUse:['감량/지구력'],
    goals:['지속 능력','기술 유지'],
    pros:['안정적 부하'],
    cons:['강도 낮을 수 있음'],
    cautions:['폼 유지'],
    zones:['Z1','Z2'],
    examples25:['200 easy + 6×50 steady + 200 easy'],
    examples50:['4×100 steady + 4×50 easy'],
    recommendedDrillIds:['fs_fingertip'] },

  { id:'quality', name:'Quality over Quantity',
    definition:'적은 반복을 고품질로 집중 수행.',
    whenToUse:['시간 제한','피크 품질'],
    goals:['기술/속도 품질'],
    pros:['효율↑'],
    cons:['총볼륨↓'],
    cautions:['휴식 충분'],
    zones:['Z4','Z5'],
    examples25:['10×25 fast, full rest'],
    examples50:['8×50 RP focus, r40″'],
    recommendedDrillIds:['fs_streamline'] },

  { id:'progress', name:'Progressive Overload',
    definition:'주차별 볼륨↑/레스트↓로 점진 부하.',
    whenToUse:['장기 계획'],
    goals:['지속 향상'],
    pros:['체계적'],
    cons:['과부하 위험'],
    cautions:['ACWR 0.8~1.3 유지'],
    zones:['Z2','Z3'],
    examples25:['주차별 5~10% 증량'],
    examples50:['레스트 주차별 −5″'],
    recommendedDrillIds:[] },

  { id:'recovery', name:'Recovery Flush',
    definition:'아주 가볍게 혈류/회복.',
    whenToUse:['강한 날 다음날'],
    goals:['피로 제거','부상 예방'],
    pros:['회복↑'],
    cons:['자극 낮음'],
    cautions:['지루함 방지'],
    zones:['Z1'],
    examples25:['600–1000 easy mix'],
    examples50:['8×50 easy, r15″'],
    recommendedDrillIds:['fs_scull1','st_streamline'] },

  { id:'skps', name:'SKPS',
    definition:'Swim-Kick-Pull-Swim 순환 블록.',
    whenToUse:['기본기/밸런스'],
    goals:['전신 밸런스'],
    pros:['루틴화 쉬움'],
    cons:['시간 소모'],
    cautions:['각 파트 과다 금지'],
    zones:['Z1','Z2'],
    examples25:['(S100-K50-P50-S100) × 2'],
    examples50:['S200-K100-P100-S200'],
    recommendedDrillIds:['fs_6_1_6','br_kick_back'] },
];

export function findMethodById(id: string): TrainingMethod | undefined {
  const low = id.toLowerCase();
  return TRAINING_METHODS.find(m => m.id.toLowerCase()===low || m.name.toLowerCase()===low);
}

export function suggestDrillsForMethod(methodId: string): string[] {
  const m = findMethodById(methodId);
  return m ? m.recommendedDrillIds : [];
}









